### ISSUE TITLE
Can you explain me how to connect to the camera

### ISSUE THREAD

**Issue by PinkMediaGroup** [zeplin455/MediapipeUE#1]
Thank you for sharing the plugin.

Can you explain me how to connect the webcam to the mediapipe plugin?

**Comment by zeplin455** [comment]
Hi, Sorry you stumbled upon the project in a early state. There is still much to be done in terms of calculating things from the input data, aligning to unreal axis and documentation that I haven't got to yet but to answer your question, 
There is a simple tracker written in python which I intend to ultimately build into an exe the same way that the OpenSee tracker is built (VSeeFace's tracker). It can be found here: [MediaPipeTrackingPy](https://github.com/zeplin455/MediapipeTrackingPy).

Easiest at the moment would be to open it in PyCharm and run it in there.
You can adjust the deviceid in the tracker to match your camera which will likely be 0 (1 for me which is currently set in that script). A lot of the other parameters doesn't do anything yet
![image](https://user-images.githubusercontent.com/24256332/145952261-83806133-41ea-41f7-922c-f862e0b5d8ea.png)

Nothing specific needs to be done for connections as the unreal component will just listen and the tracker will send so once both are running the data will be fed into unreal and it can be used however you see fit.

You'll have an actor with components like this.
![image](https://user-images.githubusercontent.com/24256332/145952914-0e44e7d5-2a2e-43c4-87c7-0c9dd83229ac.png)

The mediapipe component handles the communication so it ouputs the raw tracking points through a OnReceivedData event and then the MediapipeFace is intended to deal with the face tracking data coming from it, the MediapipeHandsPlain is intended to deal with the hand data and the MediapipePose component is intended to deal with the pose information. The hands and face are somewhat useable but the pose component is still heavy WIP.

Here are some important blueprint snips:
![image](https://user-images.githubusercontent.com/24256332/145953535-5dda0700-c52f-48c6-983b-9357a1f7692e.png)

![image](https://user-images.githubusercontent.com/24256332/145953591-19b45b95-6955-4c0a-932c-0352ebfcac40.png)

![image](https://user-images.githubusercontent.com/24256332/145953688-cf0131c1-7514-470f-ab39-b8607361ace5.png)

**Comment by zeplin455** [comment]
Instructions on the tracking points like labels and indexes can be found here:
[Mediapipe](https://google.github.io/mediapipe/)
